### PR TITLE
Pull Request for Newsweek Project (Bootstrap)

### PR DESCRIPTION
**Pull request by teekaytech**
## Greetings,

I have successfully completed my clone copy of the Newsweek homepage project. 
I, therefore, open this pull request for review by TSE.

Thank you.

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
## Hi @teekaytech . 👨‍🚀  
### Very good job so far.
* Your README file is clear and descriptive.
* The Html Validator doesn't inform any warning or error.
* Commits messages are clear and descriptive.
* You don't use inline styling, so its a good coding practice.

However, the following issues need to be implemented/fixed to consider this project as approved  👨‍💻  ⬇️ 

****
- [ ] No lint configuration on repository.
There's no setup on the repository to stickler, you can do this following this [guide](https://github.com/microverseinc/linters-config).
****
- [ ] Pull request.
Your pull request it's ok, but we can improve it adding a short description of what you did, also you can add a list with 3 or 4 points. 
Here' a [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) with more information about how and why it is important.
****
- [ ] Navbar 'Sign In' button.
The 'sign in' should be a button or in this case you used a 'span' tag so kindly please add a 'hover' property to give the clickable behavior as a button.
****
- [ ] Navbar search box.
There's an issue on 'md' and 'lg' size where the search box gets is pressed down.
You can achieve this by giving a dynamic size for each 'li' element on your 'ul' using percentages, or put a max width of 100% on your 'ul' element.
Screen Shot 2020-04-02 at 11 33 13 PM
****
- [ ]  Hamburger menu button and spacing.
From 'md' size and earlier, the navbar changes to the small size and appears the hamburger menu button.
The latter like the 'sign in' should behave like a button. 
Please make the changes listed above to achieve that.
Also, please center your element using 'justify-content' property, add the spacing between the hamburger button and the  'sign in' and 'subscribe' button and reduce the height of the navbar container and Newsweek logo to make it look as much as possible like the page on which the project is based. 😄 
Reference images below.
How it looks now. ⬇️ 
Screen Shot 2020-04-02 at 11 40 00 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-02 at 11 40 06 PM

****
- [ ] Section Titles.
Please style your titles of each section to make it look as much as possible like the page on which the project is based. 👨‍💻 
How it looks now. ⬇️ 
Screen Shot 2020-04-02 at 11 44 41 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-02 at 11 45 26 PM

****
- [ ] Debate section. 
The debate section doesn't have the images of the author. Please add it.
How it looks now. ⬇️ 
Screen Shot 2020-04-02 at 11 47 35 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-02 at 11 47 45 PM

****
- [ ] Opinion section.
Your work so far was very good, there's a couple of styling details to make it looks awesome!
Please check the images below and style this section to looks much similar as possible to the original page.
Descriptive images below, both are on the same screen sizes ('md').
How it looks now. ⬇️ 
Screen Shot 2020-04-02 at 11 50 45 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-02 at 11 50 51 PM

As you can notice your opinion section is too big, please reduce the sizes of the author's images, you can implement media queries that only enables on 'md' sizes and earlier sizes.
****
- [ ] I notice you use the bootstrap properties to give color to the items of the whole page, 
Although this is not bad, it can become a complication and too confusing if future changes are required or if you want to change the color of the entire page, for that reason it is recommended to use bootstrap only to position elements and for stylization implement specific classes that apply to the necessary elements.
****
### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  


**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by teekaytech** [comment]
Thank you, David. 

# I've gone through thee changes required as stated above and I have made all the necessary changes. 

In this project, I did the following:

- Added my contents from the official Newsweek homepage
- Use twitter bootstrap classes for styling and responsiveness
- Try as much as possible to avoid customized styling
- Cross-check the look of the components in different screen sizes.

**Comment by teekaytech** [comment]
Thank you, David.

# I've gone through thee changes required as stated above and I have made all the necessary changes.
In this project, I did the following:

- Added my contents from the official Newsweek homepage
- Use twitter bootstrap classes for styling and responsiveness
- Try as much as possible to avoid customized styling
- Cross-check the look of the components in different screen sizes.

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :100: :1st_place_medal: 

Hi @teekaytech :smile_cat: :smile_cat: 

You did all the required changes asked by David(TSE), good job taking care about his recommendations :muscle: 
### **So, your project was approved** :fireworks: :fireworks: :fireworks: :fireworks: Congrats for the beautiful and professional project :+1: :+1: 


SUGGESTION FOR THE NEXT PROJECTS:

:v: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''newsweek-page'' instead of ''dev", for example. It will be more descriptive :+1: 
The way that we have to use ''development" branch will be required on the Ruby section :+1: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
